v0.1
xakepon/java-shareit pull request #1
Opened 2024-05-30 18:16 UTC by xakepon

2024-05-31 08:43 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-05-31 08:43 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
Это класс-помощник, стоит оформить его стандартными способами. В этой статье описано, как:

https://www.baeldung.com/java-helper-vs-utility-classes

2024-05-31 08:43 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
Про это уже писал

2024-05-31 08:43 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequestMapper.java
> +public class ItemRequestMapper {
Про это писал уже

2024-05-31 08:43 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +public class UserMapper {
Про это писал уже

2024-05-31 08:43 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +        return users.values().stream()
Это действие выполняется за `O(n)`, где `n` -- количество пользователей. 
Если завести еще одну коллекцию, то можно реализовать эту проверку за `O(1)`

2024-05-31 08:43 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +                });
Для этого можно воспользоваться методом, который уже есть в `Storage` и не перебирать всю коллекцию целиком

2024-06-04 19:55 UTC, xakepon commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +public class BookingMapper {
классы сделал final, статическими методы пока не сделал, надо подумать как ряд методов переделать, позанимаюсь над этим вопросом

2024-06-04 19:56 UTC, xakepon commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +public class ItemMapper {
классы сделал final, статическими методы пока не сделал, надо подумать как ряд методов переделать, позанимаюсь над этим вопросом

2024-06-04 19:56 UTC, xakepon commented on src/main/java/ru/practicum/shareit/request/ItemRequestMapper.java
> +public class ItemRequestMapper {
классы сделал final, статическими методы пока не сделал, надо подумать как ряд методов переделать, позанимаюсь над этим вопросом

2024-06-04 19:56 UTC, xakepon commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +public class UserMapper {
классы сделал final, статическими методы пока не сделал, надо подумать как ряд методов переделать, позанимаюсь над этим вопросом

2024-06-04 19:56 UTC, xakepon commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +        return users.values().stream()
завел новую коллекцию по электронным почтам, надеюсь я правильно понял идею.

2024-06-04 19:58 UTC, xakepon commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +                });
пытался сделать как писал и пример в пачке пытался проработать,  Пока в комментарии, еще попробую проработать вопрос

2024-06-05 17:07 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-06-05 17:07 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserStorageImpl.java
> +       return emailsUsers.values().stream()
А почему не просто `get`?

2024-06-18 20:52 UTC, merged