Add bookings
xakepon/java-shareit pull request #2
Opened 2024-06-18 20:53 UTC by xakepon

2024-06-19 08:25 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDto getById(Long userId, Long bookingId) {
Здесь достаточно `readonly`-транзакции

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAllUserBookings(Long userId, String state) {
Аналогично про `readonly`-транзакцию

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAllOwnerBookings(Long ownerId, String state) {
Аналогично `readonly`-транзакция

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
>      public ItemDto toItemDto(Item item) {
Этот метод может быть статическим

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public Item toItem(ItemDto itemDto) {
Этот метод может быть статическим

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public void updateItemDto(ItemDto itemDto, Item itemToUpdate) {
Этот метод может быть статическим

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
>  @Component
На самом деле это не компонент, а класс-помощник. Здесь можно почитать, как его правильнее организовать:
https://www.baeldung.com/java-helper-vs-utility-classes

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>          return items;
`readonly`-транзакции

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/comment/CommentMapper.java
> +    private ItemMapper itemMapper;
Если все методы в `ItemMapper` будут статическим, то он не нужен тут будет в качестве параметра, а значит этот класс тоже станет классом-помощником

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/comment/CommentServiceImpl.java
> +    }
`readonly`-транзакции

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequestMapper.java
> +    public ItemRequestDto toItemRequestDto(ItemRequest itemRequest, Long userId) {
Лучше в `mapper` передавать уже готовые параметры на вход, чтобы он занимался только маппингом, а не поиском в том числе, ну и тогда аналогично его можно будет переделать в класс-помощник

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +public interface ItemRequestService {
Зачем нам пустой интерфейс и его пустая реализация?

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
>  public final class UserMapper {
Методы можно сделать статическими

2024-06-19 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>      }
`readonly`-транзакция

2024-06-19 08:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +    text VARCHAR(1000) NOT NULL,
если называем поле в таблице, как тип данных, то стоит его экранировать \`\`

2024-06-19 20:32 UTC, xakepon commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDto getById(Long userId, Long bookingId) {
добавил аннотацию readonly

2024-06-19 20:32 UTC, xakepon commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAllUserBookings(Long userId, String state) {
добавил аннотацию readonly

2024-06-19 20:32 UTC, xakepon commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingDto> getAllOwnerBookings(Long ownerId, String state) {
добавил аннотацию readonly

2024-06-19 21:09 UTC, xakepon commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
>      public ItemDto toItemDto(Item item) {
сделал

2024-06-19 21:09 UTC, xakepon commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public Item toItem(ItemDto itemDto) {
сделал

2024-06-19 21:10 UTC, xakepon commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public void updateItemDto(ItemDto itemDto, Item itemToUpdate) {
сделал

2024-06-19 21:16 UTC, xakepon commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
>  @Component
Приложение сразу падает, хотя вроде везде сделал статический вызов методов маппера, если будет возможность то подскажи пожалуйста куда капнуть...

2024-06-19 21:19 UTC, xakepon commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>          return items;
сделал

2024-06-19 21:22 UTC, xakepon commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
>  @Component
разобрался и сделал

2024-06-19 21:26 UTC, xakepon commented on src/main/java/ru/practicum/shareit/item/comment/CommentMapper.java
> +    private ItemMapper itemMapper;
сделал

2024-06-19 21:28 UTC, xakepon commented on src/main/java/ru/practicum/shareit/item/comment/CommentServiceImpl.java
> +    }
сделал

2024-06-19 21:33 UTC, xakepon commented on src/main/java/ru/practicum/shareit/request/ItemRequestMapper.java
> +    public ItemRequestDto toItemRequestDto(ItemRequest itemRequest, Long userId) {
сделал, если все правильно понял

2024-06-19 21:34 UTC, xakepon commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +public interface ItemRequestService {
был задел на будущее, удалил

2024-06-19 21:37 UTC, xakepon commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
>  public final class UserMapper {
сделал

2024-06-19 21:38 UTC, xakepon commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
>      }
сделал

2024-06-19 21:48 UTC, xakepon commented on src/main/resources/schema.sql
> +    text VARCHAR(1000) NOT NULL,
сделал

2024-06-19 22:04 UTC, xakepon commented on src/main/resources/schema.sql
> +    text VARCHAR(1000) NOT NULL,
после экранирования постман тесты именно в гите упали...
вообще делал так "text" VARCHAR(1000) NOT NULL,
и самое главное на ноуте постман все без ошибок проводит, отпишу куратору чтобы пересмотрели тесты в постмане с этим моментом экранирования

2024-06-20 12:49 UTC, LexLippi commented on src/main/resources/schema.sql
> +    text VARCHAR(1000) NOT NULL,
Хорошо, оставь как работает :)

2024-06-20 12:49 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-06-26 19:08 UTC, merged